#!/bin/bash
#mpif90 -c -convert little_endian -FR mpi_module.f
#mpif90 -c -convert little_endian -I$NETCDF/include module_netcdf.f
#mpif90 -c -convert little_endian -assume byterecl -traceback -FR -I$NETCDF/include -I/work2/06191/tg854905/stampede2/opt/CRTM/PSU_EnKF_CRTM/crtm_v2.3.0/include XbtoIR_crtm.f90
#mpif90 -o XbtoIR_crtm.exe mpi_module.o module_netcdf.o XbtoIR_crtm.o -L/work2/06191/tg854905/stampede2/opt/CRTM/PSU_EnKF_CRTM/crtm_v2.3.0/lib -lCRTM -L$NETCDF/lib -lnetcdff  
#mpif90 -o crtm.exe mpi_module.o module_netcdf.o main_crtm.o -L/work2/05747/cxh416/stampede2/CRTM/lib -lcrtm -L$NETCDF/lib -lnetcdff  


CRTM_DIR="/work2/06191/tg854905/stampede2/opt/CRTM/PSU_EnKF_CRTM/crtm_v2.3.0/"
#FCFLAG=-f90=ifort -convert little_endian -traceback -I$(QN2RE)
echo ${CRTM_DIR}


mpif90 -f90=ifort -c -i4 -w -ftz -align all -fno-alias -fp-model precise -assume realloc_lhs -convert little_endian -traceback -MIC -AVX512 -FR  mpi_module.f
mpif90 -f90=ifort -c -i4 -w -ftz -align all -fno-alias -fp-model precise -assume realloc_lhs -convert little_endian -traceback -MIC -AVX512 -I$NETCDF/include  module_netcdf.f
mpif90 -f90=ifort -c -i4 -w -ftz -align all -fno-alias -fp-model precise -assume realloc_lhs -convert little_endian -traceback -MIC -AVX512 -FR -I$NETCDF/include -I$CRTM_DIR/include XbtoIR_crtm.f90
# apparently replace the above line with below if using newer netcdfs
mpif90 -o XbtoIR_crtm.exe mpi_module.o module_netcdf.o XbtoIR_crtm.o -L$CRTM_DIR/lib -lcrtm -L$NETCDF/lib -lnetcdff 
