#!/bin/bash
#SBATCH --job-name="ProcessMW"
#SBATCH --output="log"
#SBATCH --partition=compute
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=8
#SBATCH --account=pen116
#SBATCH --export=ALL
#SBATCH -t 01:30:00

#This job runs with 2 nodes, 128 cores per node for a total of 256 tasks.

matlab -batch main_process_MWobs

