#!/bin/bash
#SBATCH --job-name="ProcessMW"
#SBATCH --output="out"
#SBATCH --partition=shared
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=8
#SBATCH --account=pen116
#SBATCH --export=ALL
#SBATCH -t 02:00:00
#SBATCH --mail-user=yao.zhu.91@gmail.com
#SBATCH --mail-type=all

matlab -batch main_process_MWobs > log

